#!/usr/bin/env rake

require 'bundler/setup'
Bundler.require(:default)

# general environment task to set up AR and logging
task :environment do
  ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml')))
  ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
end

# snarf task

# console task

# report tasks
