
require 'bundler/setup'
Bundler.require(:default)
require 'active_record'
require 'logger'
require 'sqlite3'
require 'uuid'
require 'factory_girl'

Factory.find_definitions

require_relative File.join('.','models')

task :environment do
  ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml')))
  ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
end

namespace :db do

  desc "Run ActiveRecord Migrations"
  task :migrate => :environment do
    ActiveRecord::Migration.verbose = true
    ActiveRecord::Migrator.migrate('db/migrate')
  end

  desc "Snarf Schema"
  task :snarf => :environment do
    puts ActiveRecord::SchemaDumper.dump
  end

end

desc "Start a console"
task :console => :environment do
  require 'irb'
  ARGV.clear
  IRB.start
end
